### ISSUE TITLE
PR#27 – meta["categories"] = (meta["categories"] || []).to_set

### ISSUE THREAD

**Issue by RalphHightower** [RalphHightower/blog#26]
Generating: JekyllOptionalFrontMatter::Generator finished in 3.5226e-05 seconds.
bundler: failed to load command: jekyll (/home/runner/work/blog/blog/vendor/bundle/ruby/3.3.0/bin/jekyll)
/home/runner/work/blog/blog/vendor/bundle/ruby/3.3.0/gems/jekyll-feed-0.17.0/lib/jekyll-feed/generator.rb:72:in `block in collections': undefined method `[]' for nil (NoMethodError)

        meta["categories"] = (meta["categories"] || []).to_set
                                  ^^^^^^^^^^^^^^
	from /home/runner/work/blog/blog/vendor/bundle/ruby/3.3.0/gems/jekyll-feed-0.17.0/lib/jekyll-feed/generator.rb:71:in `each_value'

_Originally posted by @RalphHightower in https://github.com/RalphHightower/blog/issues/25#issuecomment-2365444861_

**Comment by RalphHightower** [comment]
Linked to PR#25 after run.
