### ISSUE TITLE
PR#475: An npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) must be created and set in the NPM_TOKEN environment variable on your CI environment.

### ISSUE THREAD

**Issue by RalphHightower** [RalphHightower/blog#476]
```
npx semantic-release@v24.2.0
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
    NPM_TOKEN: 
[4:20:18 AM] [semantic-release] › ℹ  Running semantic-release version 24.2.0
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[4:20:19 AM] [semantic-release] › ✔  Run automated release from branch main on repository git+https://github.com/RalphHightower/blog.git
[4:20:20 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[4:20:20 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[4:20:20 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[4:20:20 AM] [semantic-release] › ✘  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[4:20:20 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[4:20:20 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[4:20:20 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[4:20:20 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[4:20:20 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[4:20:20 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[4:20:20 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[4:20:20 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[4:20:20 AM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #474.
[4:20:21 AM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #474: https://github.com/RalphHightower/blog/issues/474#issuecomment-2537780844.
[4:20:21 AM] [semantic-release] › ✘  ENONPMTOKEN No npm token specified.
[4:20:21 AM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
An npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) must be created and set in the NPM_TOKEN environment variable on your CI environment.

Please make sure to create an npm token (https://docs.npmjs.com/getting-started/working_with_tokens#how-to-create-new-tokens) and to set it in the NPM_TOKEN environment variable on your CI environment. The token must allow to publish to the registry https://registry.npmjs.org/.

AggregateError: 
    SemanticReleaseError: No npm token specified.
        at default (file:///home/runner/work/blog/blog/node_modules/@semantic-release/npm/lib/get-error.js:7:10)
        at default (file:///home/runner/work/blog/blog/node_modules/@semantic-release/npm/lib/set-npmrc-auth.js:35:31)
        at default (file:///home/runner/work/blog/blog/node_modules/@semantic-release/npm/lib/verify-auth.js:17:9)
        at verifyConditions (file:///home/runner/work/blog/blog/node_modules/@semantic-release/npm/index.js:33:13)
        at async validator (file:///home/runner/work/blog/blog/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///home/runner/work/blog/blog/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
        at async Promise.all (index 0)
        at async next (file:///home/runner/work/blog/blog/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44)
    at file:///home/runner/work/blog/blog/node_modules/semantic-release/lib/plugins/pipeline.js:55:13
    at async pluginsConfigAccumulator.<computed> [as verifyConditions] (file:///home/runner/work/blog/blog/node_modules/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///home/runner/work/blog/blog/node_modules/semantic-release/index.js:106:3)
    at async Module.default (file:///home/runner/work/blog/blog/node_modules/semantic-release/index.js:278:22)
    at async default (file:///home/runner/work/blog/blog/node_modules/semantic-release/cli.js:55:5) {
  errors: [
    SemanticReleaseError: No npm token specified.
        at default (file:///home/runner/work/blog/blog/node_modules/@semantic-release/npm/lib/get-error.js:7:10)
        at default (file:///home/runner/work/blog/blog/node_modules/@semantic-release/npm/lib/set-npmrc-auth.js:35:31)
        at default (file:///home/runner/work/blog/blog/node_modules/@semantic-release/npm/lib/verify-auth.js:17:9)
        at verifyConditions (file:///home/runner/work/blog/blog/node_modules/@semantic-release/npm/index.js:33:13)
        at async validator (file:///home/runner/work/blog/blog/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///home/runner/work/blog/blog/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
        at async Promise.all (index 0)
        at async next (file:///home/runner/work/blog/blog/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44) {
      code: 'ENONPMTOKEN',
      details: 'An [npm token](https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) must be created and set in the `NPM_TOKEN` environment variable on your CI environment.\n' +
        '\n' +
        'Please make sure to create an [npm token](https://docs.npmjs.com/getting-started/working_with_tokens#how-to-create-new-tokens) and to set it in the `NPM_TOKEN` environment variable on your CI environment. The token must allow to publish to the registry `https://registry.npmjs.org/`.',
      semanticRelease: true,
      pluginName: '@semantic-release/npm'
    }
  ]
}
Error: Process completed with exit code 1.

_Originally posted by @RalphHightower in https://github.com/RalphHightower/blog/issues/475#issuecomment-2537782477_
            
```

**Comment by RalphHightower** [comment]
The NPM_TOKEN, classic token created by npmjs.com for automation, must be stored in the repository secrets.
