### ISSUE TITLE
PR#51 'plugins' should be set as an array of gem-names, but was: nil. Use 'plugins_dir' instead to set the directory for your non-gemified Ruby plugins.

### ISSUE THREAD

**Issue by RalphHightower** [RalphHightower/blog#52]
Configuration file: /home/runner/work/blog/blog/_config.yml
'plugins' should be set as an array of gem-names, but was: nil. Use 'plugins_dir' instead to set the directory for your non-gemified Ruby plugins. 
bundler: failed to load command: jekyll (/home/runner/work/blog/blog/vendor/bundle/ruby/3.3.0/bin/jekyll)
/home/runner/work/blog/blog/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/configuration.rb:309:in `check_plugins': 'plugins' should be set as an array, but was: nil. (Jekyll::Errors::InvalidConfigurationError)
	from /home/runner/work/blog/blog/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/configuration.rb:224:in `validate'
	from /home/runner/work/blog/blog/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/configuration.rb:206:in `read_config_files'
	from /home/runner/work/blog/blog/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll.rb:118:in `configuration'
	from /home/runner/work/blog/blog/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/command.rb:44:in `configuration_from_options'

_Originally posted by @RalphHightower in https://github.com/RalphHightower/blog/issues/51#issuecomment-2367181396_

**Comment by RalphHightower** [comment]
No change. Linke on main page work, but no link to blogg page.

Also, minima is not being used. Times Roman instead of sans serif font. No borders on tablesl
